spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: homestay-booking

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/homestay_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
